In [3]:
import numpy as np

arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr1 = np.arange(20,31)
arr1

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [5]:
#Array with Array
arr + arr1

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40])

In [6]:
arr * arr1

array([  0,  21,  44,  69,  96, 125, 156, 189, 224, 261, 300])

In [15]:
#Array with Scalar
result = arr1 - 10
result

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [13]:
np.max(arr1)


30

In [16]:
result = arr1 - 13
np.max(result)

17